In [7]:
from transformers import AutoTokenizer
tokenizer = AutoTokenizer.from_pretrained('AIRI-Institute/gena-lm-bert-base-fly')
print(tokenizer.pad_token_id)
print(tokenizer.eos_token_id)
print(tokenizer.bos_token_id)
print(tokenizer.cls_token_id)
print(tokenizer.mask_token_id)
print(tokenizer.sep_token_id)
print(tokenizer.unk_token_id)

3
None
None
1
4
2
0

In [10]:
import pandas as pd

df = pd.read_csv('/mnt/mr01-home01/m65338lb/projects/mRNA_LLM-worktrees/translationEfficiency/output/predict/token_shuffle_analysis.csv')
df = df[~df['original_token'].isin([1,2])]

In [11]:
df['original_token'].unique()

array([   -1,   128,   329,  9319,    18,  2066,  3804, 14173,    24])

In [16]:
print(df[df['new_token'] == 0]['pred_change'].abs().mean())
df[df['new_token'] == 0]

0.005763456225395151

,position,original_token,new_token,prediction,label,is_original,pred_change
32000,1,128,0,1.055396,0.901654,False,0.005167
63999,2,329,0,1.053032,0.901654,False,0.002803
95998,3,9319,0,1.047374,0.901654,False,-0.002855
127997,4,18,0,1.059252,0.901654,False,0.009023
191995,6,2066,0,1.065968,0.901654,False,0.015739
223994,7,3804,0,1.048207,0.901654,False,-0.002022
255993,8,14173,0,1.056651,0.901654,False,0.006422
287992,9,24,0,1.052306,0.901654,False,0.002077

In [20]:
print(df[df['new_token'] == 4]['pred_change'].abs().mean())
df[(df['new_token'] == 4) | (df['position'] == -1)]

0.004991039633750876

,position,original_token,new_token,prediction,label,is_original,pred_change
0,-1,-1,-1,1.050229,0.901654,True,NaN
32004,1,128,4,1.053308,0.901654,False,0.003079
64003,2,329,4,1.052528,0.901654,False,0.002299
96002,3,9319,4,1.044910,0.901654,False,-0.005319
128001,4,18,4,1.055554,0.901654,False,0.005324
191999,6,2066,4,1.061535,0.901654,False,0.011306
223998,7,3804,4,1.040375,0.901654,False,-0.009854
255997,8,14173,4,1.052045,0.901654,False,0.001816
287996,9,24,4,1.049298,0.901654,False,-0.000931